/** Auto-generated by scripts/optimize-images.mjs — do not edit */
export const imageManifest = {
  "adriatic": {
    "base": "adriatic",
    "width": 1600,
    "height": 1067,
    "fallbackWidth": 800,
    "fallbackHeight": 534,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "city": {
    "base": "city",
    "width": 1600,
    "height": 1203,
    "fallbackWidth": 800,
    "fallbackHeight": 602,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "coast": {
    "base": "coast",
    "width": 1600,
    "height": 1067,
    "fallbackWidth": 1600,
    "fallbackHeight": 1067,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "coastal": {
    "base": "coastal",
    "width": 1600,
    "height": 1067,
    "fallbackWidth": 1600,
    "fallbackHeight": 1067,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "compare": {
    "base": "compare",
    "width": 1600,
    "height": 1067,
    "fallbackWidth": 1600,
    "fallbackHeight": 1067,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "cruise-port": {
    "base": "cruise-port",
    "width": 1600,
    "height": 2407,
    "fallbackWidth": 1600,
    "fallbackHeight": 2407,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "family": {
    "base": "family",
    "width": 800,
    "height": 533,
    "fallbackWidth": 800,
    "fallbackHeight": 533,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "food": {
    "base": "food",
    "width": 800,
    "height": 533,
    "fallbackWidth": 800,
    "fallbackHeight": 533,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "food-and-wine": {
    "base": "food-and-wine",
    "width": 800,
    "height": 533,
    "fallbackWidth": 800,
    "fallbackHeight": 533,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "greeting-to-the-sun": {
    "base": "greeting-to-the-sun",
    "width": 1600,
    "height": 1067,
    "fallbackWidth": 800,
    "fallbackHeight": 534,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "hero": {
    "base": "hero",
    "width": 1600,
    "height": 2407,
    "fallbackWidth": 1600,
    "fallbackHeight": 2407,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "hero-home": {
    "base": "hero-home",
    "width": 1600,
    "height": 2407,
    "fallbackWidth": 1600,
    "fallbackHeight": 2407,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "highlights": {
    "base": "highlights",
    "width": 1600,
    "height": 1033,
    "fallbackWidth": 800,
    "fallbackHeight": 517,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "historic": {
    "base": "historic",
    "width": 800,
    "height": 533,
    "fallbackWidth": 800,
    "fallbackHeight": 533,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "krka-waterfalls": {
    "base": "krka-waterfalls",
    "width": 800,
    "height": 516,
    "fallbackWidth": 800,
    "fallbackHeight": 516,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "nature": {
    "base": "nature",
    "width": 800,
    "height": 516,
    "fallbackWidth": 800,
    "fallbackHeight": 516,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "og-default": {
    "base": "og-default",
    "width": 1280,
    "height": 853,
    "fallbackWidth": 1280,
    "fallbackHeight": 853,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ],
    "og": {
      "width": 1200,
      "height": 630
    },
    "ogSrc": "/images/opt/og-default-og1200.jpg"
  },
  "old-town": {
    "base": "old-town",
    "width": 800,
    "height": 533,
    "fallbackWidth": 800,
    "fallbackHeight": 533,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "photography": {
    "base": "photography",
    "width": 1600,
    "height": 1067,
    "fallbackWidth": 1600,
    "fallbackHeight": 1067,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "plitvice": {
    "base": "plitvice",
    "width": 800,
    "height": 516,
    "fallbackWidth": 800,
    "fallbackHeight": 516,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "private": {
    "base": "private",
    "width": 800,
    "height": 533,
    "fallbackWidth": 800,
    "fallbackHeight": 533,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "sea-organ": {
    "base": "sea-organ",
    "width": 1600,
    "height": 1067,
    "fallbackWidth": 800,
    "fallbackHeight": 534,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "walking": {
    "base": "walking",
    "width": 800,
    "height": 602,
    "fallbackWidth": 800,
    "fallbackHeight": 602,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "wine": {
    "base": "wine",
    "width": 800,
    "height": 516,
    "fallbackWidth": 800,
    "fallbackHeight": 516,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  }
} as const;

export type ImageManifestEntry = (typeof imageManifest)[keyof typeof imageManifest];
